// Code generated by foggo; DO NOT EDIT.

package server

type ServerOption interface {
	apply(*Server)
}

type PortOption struct {
	Port int
}

func (o PortOption) apply(s *Server) {
	s.Port = o.Port
}

type AddressOption struct {
	Address string
}

func (o AddressOption) apply(s *Server) {
	s.Address = o.Address
}
